version: '3'

services:
  postgres:
    image: postgres
    container_name: db-template
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: rdemora2
      POSTGRES_PASSWORD: rdemora2
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-template
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app/backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-template
    ports:
      - "5000:5000"
    depends_on:
      - backend

volumes:
  pg_data:
