name: Backend test CI

on: [pull_request]

jobs:
    test:
      runs-on: ubuntu-latest
  
      steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install dependencies
        run: |
          cd backend
          npm install
      - name: Run Tests with Coverage
        run: |
          cd backend
          npm run test:coverage
  
